version: "3.9"
services:
  front:
    container_name: charcater-geenrator-front
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./front/src:/app/src
      - ./front/index.html:/app/index.html
    build:
      context: "./front"
      dockerfile: Dockerfile.dev
    command: yarn start