version: "3.9"
services:
  front:
    container_name: character-generator-front
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
      - ./front/index.html:/app/index.html
    build:
      context: "./front"
      dockerfile: Dockerfile.dev
    command: yarn start
    networks:
      - internal
  db:
    container_name: character-generator-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: character-generator
    ports:
      - "5432:5432"
    networks:
      - internal
  back:
    container_name: character-generator-back
    restart: unless-stopped
    ports:
      - "3001:3001"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    build:
      context: "./backend"
      dockerfile: Dockerfile.dev
    command: cross-env PORT=3001 DB_HOST=host.docker.internal DB_PORT=5432 DB_USER=root DB_PASSWORD=root DB_NAME=character-generator yarn start:dev
    networks:
      - internal
  pgadmin:
    container_name: pg-agmin
    image: dpage/pgadmin4:latest
    links:
      - db
    depends_on:
      - db
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: pwdpwd
    ports:
      - "5050:80"
  proxy:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back
    networks:
      - internal

networks:
  internal: