version: "3.9"
services:
  front:
    container_name: character-generator-front
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./front/src:/app/src
      - ./front/index.html:/app/index.html
    build:
      context: "./front"
      dockerfile: Dockerfile.dev
    command: yarn start
  back:
    container_name: character-generator-back
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    build:
      context: "./backend"
      dockerfile: Dockerfile.dev
    command: go run main.go
  db:
    container_name: character-generator-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: character-generator
    ports:
      - "5432:5432"