version: "3.9"
services:
  front:
    container_name: character-generator-front
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./front/src:/app/src
      - ./front/index.html:/app/index.html
    build:
      context: "./front"
      dockerfile: Dockerfile.dev
    command: yarn start
    networks:
      - internal
  back:
    container_name: character-generator-back
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
    build:
      context: "./backend"
      dockerfile: Dockerfile.dev
    command: watchrun go run main.go
    networks:
      - internal
  db:
    container_name: character-generator-db
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: character-generator
    ports:
      - "5432:5432"
  proxy:
    container_name: nginx
    image: nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - front
      - back
    networks:
      - internal

networks:
  internal: